# default_config.toml

[snippet_types.general]
alias = ",g"
source_file = "~/.config/rsnip/general_snippets.txt"
description = "General text snippets"

[snippet_types.shell]
alias = ","
source_file = "~/.config/rsnip/shell_snippets.txt"
description = "Shell command snippets"
format = "default"

[snippet_types.snippets]
source_file = "~/.config/helix/snippets/snippets.toml"
description = "General snippets from Helix/Zed without context binding"
format = "scls"

[snippet_types.combined]
alias = ",,"
sources = ["snippets", "general", "shell"]
description = "Combined snippets"
